### ISSUE TITLE
Example systems tracker

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/CausalityTools.jl#1]
# `Systems`submodule
This is a list of examples of dynamical systems with coupling between variables, either unidirectional or multidirectional, that can be studied in the framework of time series causality methods. 

## Contributing
Do you miss a system on the list? Open an issue for the wanted system and tag this tracker. Or, even better, implement the system yourself in the`Systems` submodule and do a pull request! You can use one of the existing example in the `/systems/` subfolder as inspiration. Remember to add tests too!

### Unidirectional coupling
- [x] 2D logistic map. Unidirectional forcing from X to Y.  **[implemented in #6 ]**.
- [x] 3D logistic map. Three coupled systems with dynamical noise. From [Runge, J. "Causal network reconstruction from time series: From theoretical assumptions to practical estimation." Chaos: An Interdisciplinary Journal of Nonlinear Science 28.7 (2018): 075310](https://aip.scitation.org/doi/10.1063/1.5025050) **[implemented in #5 ].**
- [x] 2D Henon map. Unidirectional forcing from X to Y. **[implemented in #8 ]**.
- [x] 4D Henon map. One 2D Henon subsystem unidirectionally driving another 2D Henon subsystem. From [Krakovská, Anna, et al. "Comparison of six methods for the detection of causality in a bivariate time series." Physical Review E 97.4 (2018): 042207](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.97.042207) **[implemented in #15 ]**.
- [x] 3D vector autoregressive process. Unidirectional forcing X1 -> X2 - X3. From [Papana, Angeliki, et al. "Simulation study of direct causality measures in multivariate time series." Entropy 15.7 (2013): 2635-2661.](http://www.mdpi.com/1099-4300/15/7/2635/htm).**[implemented in #10 ]**.
- [ ] 2D unidirectionally coupled autogregressive processes of first order where one process contains a cosine. From [Lungarella, Max, Alex Pitti, and Yasuo Kuniyoshi. "Information transfer at multiple scales." Physical Review E 76.5 (2007): 056117](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.76.056117)
### Strange, nonchaotic maps
- [x] 3D system where X is a highly nonlinear combination of Y and Z, which involves sine and cosine terms, respectively. From [Verdes, P. F. "Assessing causality from multivariate time series." Physical Review E 72.2 (2005): 026222](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.72.026222). ** [implemented in #32 ]**
- [x] 2D map from equation 13 in [Anishchenko, Vadim S., and Galina I. Strelkova. "Irregular attractors." Discrete dynamics in Nature and Society 2.1 (1998): 53-72.](https://www.hindawi.com/journals/ddns/1998/252749/abs/). **[Implemented in #13]**
- [x] 4D transitive causal chain of coupled logistic maps, X1 -> X2 -> X3 -> X4.  [Ye, Hao, et al. "Distinguishing time-delayed causal interactions using convergent cross mapping." Scientific reports 5 (2015): 14750](https://www.nature.com/articles/srep14750) ** [implemented in #33]**

### Multidirectional
- [x] 2D bidirectionally coupled autoregressive processes of order 1. From [Krakovská, Anna, et al. "Comparison of six methods for the detection of causality in a bivariate time series." Physical Review E 97.4 (2018): 042207](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.97.042207). **[implemented in #20]**

### Unidirectional coupling
- [x] 6D Rössler-Rössler. One 3D Rössler system unidirectionally forcing another 3D Rössler subsystem. **[implemented in #11 ]**
- [x] 6D Rössler-Lorenz. One 3D Rössler system unidirectionally forcing a 3D Lorenz subsystem. From [Krakovská, Anna, et al. "Comparison of six methods for the detection of causality in a bivariate time series." Physical Review E 97.4 (2018): 042207](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.97.042207). **[implemented in #14 ]**
- [x] 3D Chua circuit system, w/ sine function nonlinearity. From [Tang, Wallace KS, et al. "Generation of n-scroll attractors via sine function." IEEE Transactions on Circuits and Systems I: Fundamental Theory and Applications 48.11 (2001): 1369-1372](Tang, Wallace KS, et al. "Generation of n-scroll attractors via sine function." IEEE Transactions on Circuits and Systems I: Fundamental Theory and Applications 48.11 (2001): 1369-1372.). **[Implemented in #19 ]**
- [x]  9D Lorenz system. Three coupled 3D Lorenz attractors with unidirectional forcing X1 -> X2 and X2 -> X3. **[implemented in #22]**

### Multidirectional coupling
- [x] 6D Chua circuit system. One 3D Chua circuit forced by a sine function bidirectionally coupled to another 3D Chua circuit forced by a sine function. The subsystems are mutually coupled by a linear
resistor. From [Murali, K., and M. Lakshmanan. "Chaotic dynamics of the driven Chua's circuit." IEEE Transactions on Circuits and Systems I Fundamental Theory and Applications 40.11 (1993): 836-840](http://repository.ias.ac.in/19449/1/374.pdf). **[implemented in #18 ]**
- [x] 9D Mediated link example. From [Krakovská, Anna, et al. "Comparison of six methods for the detection of causality in a bivariate time series." Physical Review E 97.4 (2018): 042207](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.97.042207). **[implemented in #21]**

- [x] Hindmarsh–Rose model of neuronal bursting. [Hindmarsh, James L., and R. M. Rose. "A model of neuronal bursting using three coupled first order differential equations." Proc. R. Soc. Lond. B 221.1222 (1984): 87-102](http://rspb.royalsocietypublishing.org/content/221/1222/87.short)

**Comment by kahaaga** [comment]
The example systems will be reworked/reorganized. Some of the above systems may even be removed.
