### ISSUE TITLE
Roadmap for causal graph algorithms

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/CausalityTools.jl#188]
Modern causal inference frameworks commonly utilise graph-based frameworks to infer causal relationships between multiple variables. These methods are given in various books by Pearl, Spirtes, and in a bunch of scientific papers. The documentation for  [CausalInference.jl](https://mschauer.github.io/CausalInference.jl/latest/) documentation list relevant books and papers. [Runge et al's Science paper](https://www.science.org/doi/10.1126/sciadv.aau4996) gives a nice application in the context of timeseries analysis.

The PC-algorithm, and its variants, is perhaps the most famous approach to graph-based causal inference. Below, I use the PC algorithm for illustration, which is also what is used in the Runge et al. paper linked above.

## Existing software 

There already exists a library for graph-based causal inference in Julia ([CausalInference.jl](https://mschauer.github.io/CausalInference.jl/latest/)). It currently offers two graph-based methods (PC and FCI). The interface is nice and intuitive. However, the package is pretty basic, in that it offers only one nonparametric (Kraskov knn-based) independence estimator, and one parametric (Gaussian) estimator (correlation-based). 

Much more feature-complete libraries exist in other languages (e.g. [Tetrad](https://sites.google.com/view/tetradcausal)). 

I've been deep-diving into graph-based causality methods lately, and have come to the conclusion that based on our currently offered methods (read: V2.X), we can provide a far more flexible graph-based causal inference framework than is currently offered in Julia. I'm strongly in favor of implementing everything from scratch here instead of trying to interface with libraries such as CausalInference.jl, because there are huge performance gains to be made, and because I want full and automatic compatibility with all independence testing methods we offer here. Implementing everything from scratch also means *understanding* the methods, which would not be the case (for me, at least) if simply interfacing with some external library.

## Theory 

Inferring causal relationships from graphs in the PC framework consists of the following steps:
- Start with a fully connected undirected graph `G` with `N` vertices, where `N` is the number of variables.
- Eliminate edges in `G` based on (conditional) independence tests. After eliminating edges, we're left with a *skeleton* graph, which indicates which pairs of variables are still connected after independence testing. This procedure first applies a pairwise independence test, then applies higher-order (i.e. more variables) conditional independence tests, until some user-defined threshold is reached or there are no more independence relations to test.
- Turn the undirected skeleton graph into a *partially directed* graph. This directed graph gives you the causal relationships that were inferrable from the observations.

## Implementation 

In terms of code, this procedure boils down to the following ingredients:
- Making (un)directed graphs. Relevant graph types and necessary graph query methods are available in [Graphs.jl](https://github.com/JuliaGraphs/Graphs.jl).
- Defining some `IndependenceTest`s and `ConditionalIndependenceTest`s. These are simple wrappers around any (conditional) independence measure we offer (like `MutualInformation`/`ConditionalMutualInformation`) that performs some sort of significance testing. We already implement such methods in v2.X
- Applying these independence tests to produce a skeleton graph.
- Computing a complete partially directed acyclic graph (CPDAG) from a skeleton graph. 
- Using the CPDAG to reason about causal relationships.

## Status

I've started sketching an API for causal graph discovery (but I'm waiting with submitting a PR until #187 is merged).  The status is as follows:

- [x] Independence measures. Implemented: many flavours of (conditional) mutual information, with a bunch of estimation methods.
- [x] Independence tests.  Implemented: `SurrogateTest`, `LocalPermutation`.  These are available in the "experimental" section of the 2.X docs.
- [x] Computing skeleton graph based on independence test.
- [x] Computing a partially completed CPDAG from a skeleton graph. 

TODO: 

- [x] Parametric independence tests based on correlation.
- [ ] Oracle independence test for graphs based on d-separation (for testing algorithm performance)
