### ISSUE TITLE
Review for 2.0: Make joint distance distribution compatible with independence tests

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/CausalityTools.jl#195]
The joint distance distribution also needs to be compatible with `SurrogateTest`.

## Todo: 

- [ ] Create `JointDistanceDistribution` struct with parameters.
- [ ] Deprecate old syntax.
- [ ] Tests.
- [ ] Documentation entry.
- [ ] Add entry to measure compatibility tables.
