### ISSUE TITLE
Causality detection algorithm tracker 

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/CausalityTools.jl#2]
# Causality detection algorithm tracker

This a tracker of the different causality detection algorithms that should be implemented. 

## Contributing
Feel anything is missing on the list? Contribute by implementing it yourself, or open an issue referencing the tracker. 

## List of algorithms

- [x] Transfer entropy, transfer operator grid estimator. 
- [x] Transfer entropy, transfer operator triangulation estimator.
- [x] Transfer entropy, k nearest neighbours (kNN) estimator. 
- [x] Transfer entropy, visitation frequency estimator. 
- [x] Transfer entropy, KDE estimator. 
- [x] Joint distance distribution. 
- [x] Convergent cross mapping.
